### ISSUE TITLE
Support for shoveling from non-Nimbus queues and topics

### ISSUE THREAD

**Issue by uglybugger** [NimbusAPI/Nimbus#100]
This one came up in discussions today. Where we have other applications (e.g. Microsoft CRM) that publish their own events, it'd be nice to have an elegant way to convert and republish those messages onto Nimbus-managed queues/topics.

**Comment by ma499** [comment]
We think we would like to have this capability. How about:
* Allowing injection of a custom PathFactory?
* Annotating Handlers and MessageContracts to specify a custom path?

In our case we really just want to change the prefixes (drop the t/q, and drop the namespace name). Although, to be fair, the naming convention is fairly sensible and we're thinking we could just get our other applications to use the same naming convention.
