### ISSUE TITLE
Infinitely recycling MessageReceivers on 40400

### ISSUE THREAD

**Issue by michaelnoonan** [NimbusAPI/Nimbus#130]
![image](https://cloud.githubusercontent.com/assets/1627582/4212009/9d08499a-3894-11e4-8c3d-5d75ab587020.png)
`MessagePump` is stuck in a cycle of:
1. `FetchBatch()` - `MessagingEntityNotFoundException` is thrown
2. Catch block determines it's not a TransientFault and Discards the `MessageReceiver`
3. Next iteration attempts to get a new `MessageReceiver`
4. `AzureQueueManager` decides that the entity already exists because it's in the bucket of Known entities
5. `AzureQueueManager` returns a new `MessageReceiver` that is destined to fail again
6. Go to 1.

### After some investigation we believe the repro steps are to:
1. Leave a connected application running
2. Sleep/hibernate your laptop
3. Go on holidays
4. Come back after your queues/subscriptions have been auto-deleted
5. Wake your laptop
6. Spew forth error messages to the log!

### Otherwise:
1. Start a Nimbus application
2. Delete one of the queues/subscriptions from underneath the application
3. Spew forth error messages to the log!

### Ideas:
1. Recognise the `MessagingEntityNotFoundException` for what it is, invalidate the `AzureQueueManager.KnownXXX` and have the endpoint recreate the queue/subscription
2. Add a circuit breaker for the Receiver, or an exponential backoff of some sort.

**Comment by heinrichbreedt** [comment]
any progress with this? we get this intermittently
