### ISSUE TITLE
Constrain NuGet Update-Package command to 2.1.4.0 library version

### ISSUE THREAD

**Issue by uglybugger** [NimbusAPI/Nimbus#135]
We need to allow people to run a global Update-Package command without breaking Nimbus. As we have a fairly strict dependency on the 2.1.4.0 library (at least until the next version of Windows Service Bus drops) we should constrain package upgrades to that version.

**Comment by waheedsayed** [comment]
Today's release reminded me with this restriction.
Do you really need to keep linking the future of Nimbus & Azure SB to SB for Windows Server?

It seems they'll never align in future & they follow completely different release cycles.
I genuinely wonder if there is not any benefit or real addition in the past 30+ releases of Azure SB, so Nimbus can benefit from it?

---
- Microsoft Azure Service Bus 2.5.4 (this version)  Monday, January 12 2015
- (30+ releases) !!!
- Windows Azure Service Bus 2.1.4	 Saturday, October 19 2013

**Comment by robdmoore** [comment]
I think that Windows Service Bus is incredibly useful to target. I was recently on a client site where they wanted to eventually move to Azure, but that was in progress and in the meantime they wanted to deploy on-premise using Windows Service Bus. I think we should use our influence with Microsoft to push them to align the two products better.

**Comment by DamianMac** [comment]
> Do you really need to keep linking the future of Nimbus & Azure SB to SB for Windows Server?

Yes

**Comment by waheedsayed** [comment]
@robdmoore This is for you guys to use your influence, I haven't :)

I do agree with you that targeting Windows Service Bus is important but the link between both products is an issue. Up till now, we don't have a problem to use a year old API to talk to Azure Service Bus but I'm worried about when it's no longer possible & wondering what are we missing in 30+ releases? bug fixes or enhanced performance? Release notes doesn't tell much about this.

**Comment by RyannosaurusRex** [comment]
Even going the other direction besides what @robdmoore mentioned.  My client is building an app where we estimate millions+ messages per month on the service bus.  That many messages gets VERY pricey on Azure Service Bus, but while we're building it, Azure is super cheap and really awesome.  Nimbus targeting SB for WS in addition to ASB means that if things get too expensive later on to where it makes sense to roll our own infrastructure, we can do it with nearly no changes to our codebase.  That's very important and was one of the critical features that NimbusAPI a good business decision for both the short and long-term.
