### ISSUE TITLE
PathFactory can generate invalid Queue or Topic (%20 Edition)

### ISSUE THREAD

**Issue by RyannosaurusRex** [NimbusAPI/Nimbus#161]
Related to #10, and essentially the same fix, except Sanitize needs a fix for spaces (in the form of %20) so that they get mapped to a period as well.

    The remote server returned an error: (400) Bad Request. SubCode=40000. 'https://myappname.servicebus.windows.net/Q.UserQuery%20TestCommand/?api-version=2013-10' contains character(s) that is not allowed by Service Bus. Entity segments can contain only letters, numbers, periods (.), hyphens (-), and underscores (_)..TrackingId:60e8d3be-f322-4da9-adb3-ebc120d858b9_G8,TimeStamp:12/11/2013 12:44:48 AM

**Comment by sblackler** [comment]
@DamianMac did this get patched?

**Comment by RyannosaurusRex** [comment]
Following up.  Any updates?

**Comment by DamianMac** [comment]
Hey there

Sorry, swamped... want to have a crack at it ?

**Comment by RyannosaurusRex** [comment]
No worries.  I'll try and get a patch going this weekend or next if I get some time.

**Comment by RyannosaurusRex** [comment]
Went to check out what a fix would look like and pfft, it's already done.  Added a test for spaces and did a PR, but this can be closed.
