### ISSUE TITLE
ThrottlingMessageReceiver issue

### ISSUE THREAD

**Issue by michael-wolfenden** [NimbusAPI/Nimbus#168]
We have Nimbus hosted in a console app on a Azure A1 VM (1 Core) monitoring a single queue.

We have been performing load testing by sending 500 of the same command (not all at once, but building up over a period of time).

Each time we see the following message logged numerous times:

`Lock for message ... appears to have already expired so we're not dispatching it. Watch out for clock drift between your service bus server and ....!`

and eventually we start seeing `MessageLockLostException` exceptions

This was weird because
- We had set the message lock duration of our queue to their maximum of 5 minutes
- We added logging around our command handler and could confirm that its maximum duration time was around 4 seconds

We started to investigate by patching nimbus with extra logging in the `ThrottlingMessageReceiver`

``` csharp
_logger.Debug(
    "Pre callback [MessageType:{MessageType}, MessageId:{MessageId}, CorrelationId:{CorrelationId}, Throttle Count:{ThrottleCount}]",
    m.SafelyGetBodyTypeNameOrDefault(),
    m.MessageId,
    m.CorrelationId,
    _throttle.CurrentCount
);

await _throttle.WaitAsync(_cancellationTokenSource.Token);

await callback(m);
```

And eventually as the queue builds up, we start see logs like the following where it appears that we are waiting up to 5 minutes to enter the semaphore (`await _throttle.WaitAsync(_cancellationTokenSource.Token);`)

```
13 Jan 17:20:02 +00:00 Dispatching message Contracts.Messages.UpdateStudentDetails from inputqueue.parentportal.web.rd000d3ad0024a [MessageId:c5ba273e22b74c6ca54d25109748d142, CorrelationId:c5ba273e22b74c6ca54d25109748d142]
13 Jan 17:15:07 +00:00 Pre callback [MessageType:Contracts.Messages.UpdateStudentDetails, MessageId:c5ba273e22b74c6ca54d25109748d142, CorrelationId:c5ba273e22b74c6ca54d25109748d142, Throttle Count:1]
```

This would explain the errors we are seeing.

We suspect there is a race condition around the use of `_throttle.CurrentCount`. 

We worked around the issue by replacing:

`if (_throttle.CurrentCount == 0) await Task.WhenAny(tasks);`

with 

`await Task.WhenAny(tasks)`

ensuring there is always at least one slot in the semaphore free, but after some thought came to the conclusion that this is probably sub-optimal.

**Comment by uglybugger** [comment]
Thanks for this; very interesting.

We definitely need more tests around this. I'll have a closer look at it
when I get back.


-- 
<http://www.customsig.com/Signature/Link/andrewh%40uglybugger.org>

**Comment by jferguson** [comment]
@michael-wolfenden did this patch resolve your issue?
