### ISSUE TITLE
Question on PizzaDemo OutOfMemory Exception with Windows Service Bus 1.1

### ISSUE THREAD

**Issue by jafin** [NimbusAPI/Nimbus#174]
I'm trying to figure out what I'm doing wrong in relation to an out of memory error with a sample project.  (using Build-2.0.0.91)

* I used the pizza Sample as a demo and only changed the service Bus path to a local Windows Service Bus 1.1 location.  
* I only started the web app, no services (base memory usage 80MB)
* I then pushed a few pizza requests through (~10)
* Changed the web.config (dummy line added) to recycle the appPool.
* add a new order via the UI.
* The memory usage then continually rose rapidly until we reach a out of memory exception. 

![nimbusmemory](https://cloud.githubusercontent.com/assets/127927/6075702/83581f70-ae23-11e4-9425-52860ab28133.png)

With the debugger on Pizza Demo, I get a bunch of threadaborts initially and then a endless supply of 
* A first chance exception of type 'System.CannotUnloadAppDomainException' occurred in mscorlib.dll
Additional information: Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
* some A first chance exception of type 'System.Net.Sockets.SocketException' occurred in System.ServiceModel.dll

**Comment by uglybugger** [comment]
Hi @jafin.. I'm a twit. The sample code in the web app didn't dispose of its IoC container on Application_End, which means that there were two container instances (and hence two bus instances) hanging around.

I've just pushed an update to the sample code to fix this. You should be able to pull latest from master now.

**Comment by jafin** [comment]
Thanks @uglybugger  that fixed it.
