### ISSUE TITLE
NIAttributedLabel BUG: after insert a image, do not display correctly

### ISSUE THREAD

**Issue by tyrone782** [NimbusAPI/Nimbus#176]
NIAttributedLabel *label = [[NIAttributedLabel alloc] initWithFrame:CGRectMake(10, 100, 300, 0)];
[label setLineHeight:20];
[label setNumberOfLines:0];
[label setFont:[UIFont systemFontOfSize:14]];
[label setTextColor:[UIColor blackColor]];
[label setLineBreakMode:NSLineBreakByWordWrapping];
[label insertImage:[UIImage imageNamed:@"image"] atIndex:0];
[label sizeToFit];
[self.view addSubview:label];

Display a blank.

Other, After insert image, link show incorrectly, too.

Please Fix it.

**Comment by gertjvr** [comment]
Are you sure you have the right project?

**Comment by tyrone782** [comment]
YES, If add [label setText:@"mm"]; before [label insertImage:[UIImage imageNamed:@"image"] atIndex:0];, show correctly.

**Comment by gertjvr** [comment]
Can you find any of the source code you have referenced in the project repo?

**Comment by tyrone782** [comment]
I found this function (- (void)drawTextInRect:(CGRect)rect;) not be execute. May be because of the label's text is empty. 

Do you have any thing fix it?

**Comment by gertjvr** [comment]
Pretty sure its not a nimbus issue.

**Comment by tyrone782** [comment]
My solution is: Before insert image, determine whether the text is empty, if empty then given an empty string(@" ").

**Comment by gertjvr** [comment]
Can you upload an example?

**Comment by tyrone782** [comment]
@interface NIAttributedLabel (AutoFormatEmotion)

- (void)autoFormatToEmotion;

@end

@implementation NIAttributedLabel (AutoFormatEmotion)

- (void)autoFormatToEmotion {
    NSString *string = self.text;
    
    if (string.length == 0) return;
    
    NSRegularExpression *regex = [NSRegularExpression regularExpressionWithPattern:@"\\[([\u4e00-\u9fa5|OK|NO]+)\\]"
                                                                           options:NSRegularExpressionCaseInsensitive
                                                                             error:nil];
    __block NSMutableArray *rangesArray = [NSMutableArray array];
    __block NSMutableString *mutableString = [string mutableCopy];
    __block NSInteger offset = 0;
    __block NSString* keyword = nil;
    [regex enumerateMatchesInString:string
                            options:0
                              range:NSMakeRange(0, string.length)
                         usingBlock:^(NSTextCheckingResult *result, NSMatchingFlags flags, BOOL *stop) {
                             NSRange resultRange = [result range];
                             resultRange.location += offset;
                                 // range & emotion
                             keyword = [regex replacementStringForResult:result
                                                                inString:mutableString
                                                                  offset:offset
                                                                template:@"$0"];
                             if ([[EmojiManager sharedManger] checkValidEmotion:keyword]) {
                                 NSDictionary *dict = [NSDictionary dictionaryWithObjectsAndKeys:keyword, @"keyword", NSStringFromRange(resultRange), @"range", nil];
                                 [rangesArray addObject:dict];
                                 [mutableString replaceCharactersInRange:resultRange withString:@""];
                                 offset -= resultRange.length;
                                 
                                 self.text = mutableString;
                             }
                         }];
    
//fix bug
    if (self.text.length == 0) {
        self.text = @" ";
    }
//fix bug end
    
    for (NSDictionary *dict in rangesArray) {
        NSString *keyword = [dict objectForKey:@"keyword"];
        NSRange range = NSRangeFromString([dict objectForKey:@"range"]);
        
        NSInteger index = [[EmojiManager sharedManger] indexFromEmojiName:keyword];
        if (index != NSNotFound) {
            NSString *imageName = [[EmojiManager sharedManger] emojiImageNameFromIndex:index];
            
            NSData *imageData = UIImagePNGRepresentation([UIImage imageNamed:imageName]);
            [self insertImage:[UIImage imageWithData:imageData scale:2.4f] atIndex:range.location margins:UIEdgeInsetsZero];
        }
    }
}

@end


Class EmojiManager is processing operations expression of class.

**Comment by gertjvr** [comment]
I can now say with confidence you have the wrong project. There is no
objective c in the project repo. We can't fix your issue

**Comment by DamianMac** [comment]
LOL it's the wrong Nimbus @tyrone782 
Please post in right one
