### ISSUE TITLE
Sending events/commands asynchronously with unregistered types

### ISSUE THREAD

**Issue by sblackler** [NimbusAPI/Nimbus#177]
Hi Chaps,

In development of our internal apps, we found that there is no log message if you attempt to send/publish a message if the message was not registered with the type provider. Was there any reasoning behind this, besides the eager startup scenario?

I have two branches setup here to do two things:

- Log the an error message through the `ILogger` interface when `AssertValidMessageType` is called.
- Allow the suppression of the exception raised by `AssertValidMessageType`. This still creates the queues and sends the command/event successfully.

My reasoning behind the second change of allowing the suppression is two fold; we should be able to send commands without registering them in advance (eg: plugin scenario) which then enables to setup the queues/topics at first use.

Thoughts?
Stu

**Comment by sblackler** [comment]
cc/ @BenGale

**Comment by IanYates** [comment]
After the .NET user group meeting in Brisbane there were a few of us in the lift on the way back down to ground and we were discussing this very problem.  The issue that cropped up in the (excellent) demo was that a sender type wasn't registered.  
A straw poll of each of us in the lift thought it would've been good if the library had at least thrown an exception rather than silently failing.  The plugin scenario is one we hadn't considered but makes good sense.  I guess such plugins could have their own installers/modules which are invoked by the IOC container on startup.

**Comment by DamianMac** [comment]
@IanYates I think the issue that came up in the user group talk was not in the sending, but in the receiver. We could do a check there, if you have a handler for a type that's not registered we could throw.

@sblackler would be interested to see your branch, it's an interesting idea.

**Comment by sblackler** [comment]
Yeah sure, I've got two branches that ill push up later today. I'll drop the branches in here when done.

Sent from my Windows Phone
________________________________

**Comment by sblackler** [comment]
Sorry its been a while chaps, finally got permission to get these uploaded to GH. 

So the first branch is [here](https://github.com/4Com/Nimbus/commits/feature-AllowUnregistedSending). The crux of the fix is to allow the BusCommandSender/BusEventSender to carry on if `_knownMessageTypeVerifier.AssertValidMessageType(eventType);`. This then allows the message to be sent to the bus.

The second branch is [here](https://github.com/4Com/Nimbus/commits/bug-UnregisteredCommandsFailSilently). This branch changes the `KnownMessageTypeVerifier` to take an instance of `ILogger` and write out a message during `AssertValidMessageType`.

What are your thoughts?

**Comment by DamianMac** [comment]
Have commented on your branches!
