### ISSUE TITLE
Is it possible to configure as a message sender only?

### ISSUE THREAD

**Issue by hoyleg** [NimbusAPI/Nimbus#179]
I've got a problem with an installation of Nimbus not closing down cleanly upon recompile inside a website, I believe this could be avoided entirely if the website could be set up to send messages only, as the listeners operate as web jobs.  Is this possible?

**Comment by uglybugger** [comment]
Hi @hoyleg.. Yes, it's possible (just don't call bus.Start()) but I think the root cause of your issue will be that you're not calling Dispose() on the old instance of your bus.

Are you disposing of your container in Application_End?

**Comment by hoyleg** [comment]
No, I am not. Two excellent pointers, thank you :)
