### ISSUE TITLE
Multicast Request/Response via Topics?

### ISSUE THREAD

**Issue by RyannosaurusRex** [NimbusAPI/Nimbus#180]
Here's my scenario.  I'm building a SaaS app, where I intend to have multiple tenants have their own handler for a particular request, let's call it `GetProfileRequest`, which is handled by `GetProfileRequestHandler` and returns a `GetProfileResponse`.  I intend for every request and response message to inherit from a base message that contains a `TenantId`.  The `TenantId` essentially acts as a filter for each tenant, so the handlers for each tenant can have different implementations.  Basically it's a multicast request response as described in the docs, but where I don't want multiple handlers even responding unless the TenantId is for them.

I know I can just use DI inside a single handler and swap implementations out depending on the TenantId or create a completely separate message contract per-tenant, but there's a chance that other handlers would need to be written in Java, or JS, or something else, so I'd like for them to be able to just subscribe directly to ASB and reply accordingly.  Is that currently possible in Nimbus or something that I shouldn't generally be doing?

**Comment by lukeschafer** [comment]
This actually seems useful. We do something similar with commands - we have a number of 'order types' fulfilled by different microservices, but a single message for initiating them ('SearchCommand'). We do this with events + Custom attribute filters. We have had to avoid or rework things that would be best suited to request/response to those providers based on this fact, so I can +1 this

**Comment by gertjvr** [comment]
@RyannosaurusRex we have used combination of `OutboundInterceptor` and `InboundInterceptor` to transfer and set the current user principle, by adding a token to he brokered message as a custom property. 

You could try something similar where you use an `TentantOutboundInterceptor` to set TenantId as a custom property on the outbound brokered message and on your worker you have an 'TenantInboundInterceptor` that looks for this property on the brokered message and then terminates the dispatching if the TentantId doesn't match the worker's configuration. 

Had a quick look and the exit early behavior isn't supported at the moment, current workflow is execute all `InboundInterceptors` then dispatch message then execute all `OutboundInterceptors`. Have a look at `CommandMessageDispatcher` line 81

Other way is to just place a simple `if` statement in each message handler and if the message doesn't match the current configured TentantId then exit early out of the handler. This might be the easiest way to achieve it in the short term.

Just some quick ideas how you could achieve this.:)
