### ISSUE TITLE
Not subscribing in time for an event causes you to miss it

### ISSUE THREAD

**Issue by Lavinski** [NimbusAPI/Nimbus#189]
As Nimbus creates and subscribes to topics in a lazy manner (on start and on when sending i believe). The first time I run my application I could potentially send an Event to a topic that has no subscribers yet.

For an application that knows who the subscribers are up front is there a way to create the topics and subscribers in Nimbus so that it can begin sending events before the real subscribers have started?

**Comment by DamianMac** [comment]
Nope. We found that because of ASB's ummm awesomeness, the impact on startup time was too high on a bunch of our projects. We could make it a startup option maybe.

**Comment by Lavinski** [comment]
Ok. Yeah, that would be useful.

**Comment by DamianMac** [comment]
Look forward to your PR :)
