### ISSUE TITLE
Wiki or github.io for documentation?

### ISSUE THREAD

**Issue by ma499** [NimbusAPI/Nimbus#190]
I just made a small correction to some docuentation on the wiki.
Then I realised there's a copy of the documentation on the github.io web site and I should probably raise a pull request to correct the text there?

Which should be the canonical source of documentation? (And can the other source be removed to prevent confusion?)

Or is the intention to continue to maintain two sets of documentation?

**Comment by DamianMac** [comment]
Done :)
