### ISSUE TITLE
Do I need to create a queue manually?

### ISSUE THREAD

**Issue by johnknoop** [NimbusAPI/Nimbus#196]
Hi

I've set up two different WebAPI applications and wired them up with Nimbus.Autofac. I've made sure to include all necessary assemblies to scan. Now the first application published an event like this:

```
await _bus.Publish(new QuestionAnsweredEvent {Seconds = 4});
```

The code above executes without exception, but **I can't get the event handler in the other application to trigger**. Heres the code:

```
	public class QuestionAnsweredListener : IHandleMulticastEvent<QuestionAnsweredEvent>
	{
		public Task Handle(QuestionAnsweredEvent busEvent)
		{
			throw new System.NotImplementedException();
		}
	}
```

I've verified that the bootstrapping code (the Autofac wiring) is running when both applications start.

Is it that I haven't created any topics or queues in the Azure management portal? All I've done is to create a new service bus and copy the connection string to my applications. The name of the application that I've passed to the WithNames method is just an arbitrary name. Should it be the name of a queue or a topic or something?

**Comment by uglybugger** [comment]
Hi,

You shouldn't need to create any queues manually - Nimbus does all of that for you.

One thing to check is that each of your applications is configured with a different name. If you've copied and pasted your configuration from your first app to your second, that's a likely issue.

The other thing to check is that you've called and awaited bus.Start() in each app. Without that, you'll be able to send messages but no message pumps will be running so you'll never receive anything.

Shout out if that doesn't help :)

**Comment by johnknoop** [comment]
Thanks a lot, that helped!

And awaiting the ```Start()``` of the bus also made it apparent that I need a Standard service bus, instead of the Basic one I had created.

Cheers!

**Comment by uglybugger** [comment]
You're welcome. Have fun :)
