### ISSUE TITLE
NuGet Dependencies

### ISSUE THREAD

**Issue by sblackler** [NimbusAPI/Nimbus#197]
In our internal builds of Nimbus (we have extra stuff in), we noticed that there are several outdated NuGet dependencies. This is starting to cause dependency issues with some of the MSFT libraries. Typically we have to install Nimbus first before anything else in order to get the balance just right. This is less than ideal and can cause some interesting problems...

**Comment by IanYates** [comment]
Is part of this related to #135?

**Comment by sblackler** [comment]
In a way. I just think its time to update and re-test the library against the latest versions of all the dependencies and remove the restrictions on specific versions.
