### ISSUE TITLE
Stop and start a subscriber in the middle of a message handle

### ISSUE THREAD

**Issue by ghost** [NimbusAPI/Nimbus#202]
Hi

We have a nimbus subscriber service to update an application and sometimes this application goes down. Instead of the service trying to update the application, failing, then sending the messages to deadletter, we'd like to stop or sleep the service for a time.

I've used the Bus.Start() and Bus.Stop() methods to stop/start the subscription, however have not been able to cancel a message that is currently being handled. Inside the Handle() method of IHandleMulticastEvent, when I throw it will retry 5 times until it goes to deadletter and if I return it will complete the message. How can I cancel a message so that it stays on the queue to be handled later when the subscription starts again?

In case it has an impact to the solution, we are also using ILongRunningTask.

And if there's a better way to do this (like maybe reading the deadletter queue) I'm happy to hear how to do that with nimbus too.

Thanks
Steve

**Comment by uglybugger** [comment]
Hi @stevescc! This sounds like the exact scenario that you'd want to use dead letter queues. The point of having immediate retries is for short-term, transient failures. If you have failures that last so long that you need to spin your processing apps down then I wouldn't stress too much about having a message or two be dead-lettered.

For what it's worth, it's not the handler/dispatch logic that's causing the immediate retries - that's how service bus works. What's happening is that we're calling .Abandon() on the message and the message is being immediately returned again by our .ReceiveBatch() call. If you've already spun down the bus (and hence all the message pumps) you shouldn't see another delivery attempt.

What if you were to allow the messages currently being handled to be dead-lettered on your handling app's shutdown as per normal but just poked through the dead letter queue on startup and re-submitted anything that had exceeded its retry count? You'd get the best of both worlds here - quick retries for short-term transient failures and reliable recovery for longer outages.

**Comment by stevescc** [comment]
Thankyou Andrew. 

Yes, we're looking at the scenario where the application is down for an extended period and there can be a lot of messages dead-lettered.

Your suggestion suits, as a big issue for us is that we have to manually resubmit dead-lettered messages. Is there documentation or are you able to show me how to query and resubmit the dead-letter messages with nimbus?

**Comment by stevescc** [comment]
Hi Andrew (@uglybugger), Following your suggestion we investigated subscribing to the dead-letter queue and resubmitting messages meeting certain conditions. We found we could only re-submit to the topic, not the subscription that dead-lettered the message. Therefore all subscriptions must handle the message again. Is this what you recommend?

An alternative we were thinking of was, rather than re-submit the message, directly process the message in the dead-letter subscription. Ofcourse, then we are dealing with potential dead-lettered dead-letter messages.

**Comment by uglybugger** [comment]
Hi @stevescc! It's turtles all the way down, that way :) This sounds like your event handler should be sending a command rather than doing the work itself. Your command messages could then easily be dead-lettered and resubmitted at your leisure. Does that make sense?

**Comment by stevescc** [comment]
@uglybugger Andrew, I think it makes sense. I've had a go drawing a diagram of it, is this right? Cheers
![subscriber design](https://cloud.githubusercontent.com/assets/11829532/7877125/35d027f4-0619-11e5-9ec5-ed06a456e8bf.PNG)
