### ISSUE TITLE
Automatic creation of Queues/Topics

### ISSUE THREAD

**Issue by georgemelody** [NimbusAPI/Nimbus#203]
Our connection to our production instance of Service Bus doesn't have the 'manage' permission so we wont be able to have Nimbus create our queues and topics on startup.

Do you have any advice as to how we can still use/configure Nimbus in this case?

Thanks in advance, congratulations on a great product!

**Comment by uglybugger** [comment]
Hi @georgemelody ! It'd be worth having a look at some of Nimbus's routing strategies. Based on the type names of your message contracts, you can deterministically spit out a list of queue and topic names that you could get your sysadmin overlords to create for you :)

**Comment by georgemelody** [comment]
Hi, thanks for the reply!
Yes I have tried some kind of bootstrap app that creates everything in advance, based on the naming conventions, but unfortunately when the main app runs without manage permissions it fails on bus start (and seems to suppress the exception). 

Looking at the exception thrown inside the Nimbus src this is due to not having permission when trying to get all the topics (GetTopicsAsync). This is also true for enumerating queues & subscriptions (these operations all need manage claim).
Thanks again

**Comment by mrsalty** [comment]
Hi guys, my company is in the process of adopting Nimbus and we are facing the same issue with our devops. It would be great to have an alternative for this as it might stop us from using it (and it would be a shame!). Great work guys, Nimbus rocks!

**Comment by DamianMac** [comment]
You guys want to have a crack at building some suppression options ?

**Comment by mrsalty** [comment]
I will definitely look into that.

**Comment by mrsalty** [comment]
Not a solution to this but I think the exception in case of unauthorized access to the Bus was being swallowed. I've created a pull request here :
https://github.com/NimbusAPI/Nimbus/pull/207

**Comment by mrsalty** [comment]
Hi, I've put down some code here https://github.com/NimbusAPI/Nimbus/pull/208. Have a look and let me know if you like the idea. Cheers!

Haven't implemented how to spit out a list of queues and stuff to handover to the devops guys. I was thinking to log them out during the warmup? Any idea?
