### ISSUE TITLE
Request message dispatching problem

### ISSUE THREAD

**Issue by zaccharles** [NimbusAPI/Nimbus#209]
I'm sorry for the lame title, I wasn't sure what to write. Let me set up the scenario:  

I have these two interfaces:

```
public interface IPagedBusRequest<TRequest, TResponse> : IBusRequest<TRequest, TResponse>
    where TRequest : IBusRequest<TRequest, TResponse>
    where TResponse : IPagedBusResponse
{
    int PageNumber { get; set; }
    int PageSize { get; set; }
}
```

and

```
public interface IPagedBusResponse : IBusResponse
{
    int PageNumber { get; set; }
    int PageSize { get; set; }

    int TotalCount { get; set; }
}
```

As you can see, they're just simple interfaces to ensure messages with paging are consistent. The important part is that now my messages are defined like this:

```
public class GetAccountsRequest : 
    GetAccountsRequestBase, IPagedBusRequest<GetAccountsRequest, GetAccountsResponse>
```

I have an Account service, which has a handler defined as so:

```
public class GetAccountsRequestHandler : IHandleRequest<GetAccountsRequest, GetAccountsResponse>
```

Now, when sending a `GetAccountsRequest`, my Account service is logging errors like this:

> System.InvalidOperationException: Sequence contains more than one element
>    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
>    at Nimbus.Infrastructure.RequestResponse.RequestMessageDispatcher.GetGenericDispatchMethodFor(Object request)
>    at Nimbus.Infrastructure.RequestResponse.RequestMessageDispatcher.<Dispatch>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Nimbus.Infrastructure.MessagePump.<Dispatch>d__c.MoveNext()

The `Single` call it's referring to is [this one](https://github.com/NimbusAPI/Nimbus/blob/master/src/Nimbus/Infrastructure/RequestResponse/RequestMessageDispatcher.cs#L229), though I imagine [this one](https://github.com/NimbusAPI/Nimbus/blob/master/src/Nimbus/Infrastructure/RequestResponse/MulticastRequestMessageDispatcher.cs#L213) is also a problem for multicast requests.

My solution to this was to swap `Single` for `First`. I haven't had any side effects yet, but I'm raising this issue instead of a pull request because I'm not sure this is really the correct solution.

There's a diff of the changes I made [here](https://github.com/NimbusAPI/Nimbus/compare/master...zaccharles:first?expand=1). I can raise a pull request if it's correct.

I hope I've explained this well enough...

**Comment by zaccharles** [comment]
I should add that I realise I could just add `IPagedBusRequest` and `IBusRequest` separately to `GetAccountsRequest`, but I like the idea of having a single interface and thought it should be possible.

**Comment by lukeschafer** [comment]
:+1:
