### ISSUE TITLE
Nimbus on CoreFX

### ISSUE THREAD

**Issue by KodrAus** [NimbusAPI/Nimbus#212]
Hi all,

I've started working on a new [feature branch](https://github.com/KodrAus/Nimbus/tree/dnx) that targets the new DNX Core framework. Right now I'm just hacking apart the original codebase to get a conversation going. Some of the main things I'm encountering so far:

- The Azure Service Bus library doesn't support CoreFX. So I'm currently refactoring the Service Bus calls into abstract interfaces that can use the REST API on CoreFX and the full Service Bus library on other platforms. I haven't done much analysis yet on whether there are bits not covered by Service Bus's REST API

- The threading libraries are a bit different in CoreFX. It's difficult to tell at this stage whether most of this is just cheese moving or if there are behavioural differences at runtime too

- The unit tests would need to be refactored to a framework that works with CoreFX

Does anyone have any other thoughts on this?

**Comment by gertjvr** [comment]
Started a similar exercise to introduce a different transport ie REST, WSB or Azure SB or even RabbitMQ but haven't progress any further with it.

A configurable transport layer would be an interesting idea.

**Comment by KodrAus** [comment]
The transport is both a barrier and an opportunity, isn't it. It deserves more attention than the refactoring I'm doing

**Comment by DamianMac** [comment]
My thoughts are ..... 

It's a trap!

But sounds like a fun experiment :)

**Comment by KodrAus** [comment]
Looking over the REST API support vs .NET client so far looks alright.

@DamianMac Do you know what the MSDN docs mean by [Message Enrichment](https://msdn.microsoft.com/en-us/library/azure/hh780771.aspx) which is not supported by the REST API?

**Comment by KodrAus** [comment]
With some new changes coming in #221 I'll pick this back up again when the scheduler and Service Bus dependencies are dealt with

**Comment by uglybugger** [comment]
Sounds good :)

**Comment by KodrAus** [comment]
I ran the portability analyser on the `split-transports` branch and the [results](http://nimbus-portability.azurewebsites.net/) look pretty good.

It looks like the main area for concern are performance counters and last I checked there wasn't much work done on them for .NET Core. Will have another look. Worst case scenario perf stats may not be available off Windows initially.
