### ISSUE TITLE
Ignore assembly versions in generic message types

### ISSUE THREAD

**Issue by droyad** [NimbusAPI/Nimbus#215]
Currently Nimbus stringifies the message type by calling `Type.FullName`, which includes the namespace but not the assembly information, eg `MyNamespace.AggregateRootUpdated`. This is used to figure out which type to load at the other end.

However for generic messages (eg `MyMessage<Foo>`), using `FullName` results in `MyNamespace.AggregateRootUpdated'1[MyNamespace.Foo, Bar, Version=1.0.123.0, culture=neutral, PublicKeyToken=null]`. This results in the message being unable to be processed if the sender and receiver are not currently using the same assemblies.

What if the message type is formatted as `MyNamespace.AggregateRootUpdated'1[MyNamespace.Foo]` instead?

To keep it from being a breaking change, both formats could be checked on de-serialization.

**Comment by gertjvr** [comment]
Could even use something like [ToTypeNameString TypeExtension](https://github.com/TestStack/TestStack.ConventionTests/blob/b7aac393cd36c5eecfba306f4d630dbe00e83268/TestStack.ConventionTests/ConventionData/TypeExtensions.cs#L88) that would resolve to `MyNamespace.AggregateRootUpdated<MyNamespace.Foo>`

**Comment by droyad** [comment]
Was thinking this:

	public string GetTypeName(Type type)
	{
		if(!type.IsGenericType)
			return type.FullName;
	
		var def = type.GetGenericTypeDefinition();
		var genericTypeArgsStr = string.Join(", ", type.GenericTypeArguments.Select(t => GetTypeName(t)));
		return $"{def.FullName}[{genericTypeArgsStr}]" ;
    }

**Comment by uglybugger** [comment]
3.0 is likely to have one or two breaking changes around serialization anyway so now would be a good time. We might be able to move away from the Type.FullName call altogether so this issue could end up going away all by itself. Either way it would be good to have it sorted.

**Comment by uglybugger** [comment]
Yep.. the change in serialization approach means that this is no longer an issue :)
