### ISSUE TITLE
How to achieve certain degree of parallellism for handlers?

### ISSUE THREAD

**Issue by johnknoop** [NimbusAPI/Nimbus#217]
Hi

Lets pretend I'm building a multi-tenant CQRS application where I want a message handler receiving events and saving these events in an event store. Now it's critical that these events get saved in the right order, so I probably don't want to have a bunch of different event handlers acting in parallel, because if event number 123 takes a bit longer to process than event 124, it would be saved in the wrong order in the event store. Now on the other hand, I don't want a singleton event handler for all tenants either, because that would create a bottle neck, performance-wise.

So for this reason, I would like to be able to have one handler for each tenant. Now I can make sure each message contains a property called TenantId. From there, how would I go about achieving this? Theres nothing in the wiki about this kind of setup. Is it possible now trough some kind of message routing/filtering? Will it be possible later?

Thanks in advance

**Comment by uglybugger** [comment]
Hi John! If you're building any kind of distributed system, one principle that's worth understanding is that of the constraints around message ordering and guaranteed delivery. Basically, there's no way to guarantee exactly-once delivery in order and you'll need to write your system within that constraint. For further reading on why exactly-once delivery is impossible, have a look at the Two Generals Problem.

As far as solving this problem, I'd look at adding a timestamp and a sequence number to each of your messages as well as a TenantId. That will allow your writes to your event store to be idempotent in the event of out-of-order or multiple deliveries, and will also make your handlers a whole lot less complicated.

Does that make sense?

**Comment by johnknoop** [comment]
Hi

Yea, I'm quite familiar with the at-least-once delivery, and I think I'll design for that by making the processing and storing of events completely idempotent. The event id will be created by the publisher of the event, so any writing to the data store will be an "upsert". But this is a different story.

I don't think your answer really addresses my problem. What I would like to acheive is to be able to control the degree of parallelism of my handlers. Lets say I start out with 50 tenants. Then 4 parallel handlers of each type would be a good place to start. But I want to make sure all messages (regardless of type) end up at the same handler if they have the same TenantId. Otherwise I can't guarantee the order they are stored.

Would I still be using one queue but have different topics for each tenant? Or create separate queues? I'm not even sure how to attack this problem.

Thanks

**Comment by uglybugger** [comment]
For what it's worth, there's no real way to make sure that only a specific handler receives any message. You could hack something in via a subscription filter if you wanted but I'd probably avoid that if I could.

To clarify: where are all these handlers running? Are you planning to scale out onto multiple machines but consistently handle events for a particular tenant on any particular machine?

**Comment by johnknoop** [comment]
Hi again!

Since I only have limited experience with working with message buses, want I would like to know is how to guarantee the order of stored events if they are processed in parallel. I mean, even if the queue is FIFO, the handlers might not be working in the same speed. I guess my first question could be boiled down to this:

How does Nimbus (or Azure Service Bus for that matter) behave when two events of the same type are placed on the queue? Does it

a) create an instance of the handler and execute Handle, and then immediately create another instance for the next event before the first handler is finished. Or does it

b) wait for the first handler instance to finish handling the event before creating a new instance for the next event?

My assumption is that it behaves like b, and therefor I was wondering how to make it handle up to N events of the same type in parallel. However, if the answer is a, then my question is irrelevant.

**Comment by KodrAus** [comment]
Service bus isn't too concerned with what happens to a message once it's placed in a queue, it's routing really only goes so far as ensuring any message sent to a topic is placed on all subscriptions to that topic. 

On the Nimbus end, as far as I knos it pumps messages out of queues and topic subscriptions in a batch, and each message is handled in parallel by a separate instance of a handler. So they're already parallelised by Nimbus.

**Comment by johnknoop** [comment]
Thanks!
