### ISSUE TITLE
log4net logger logs are in an incorrect format

### ISSUE THREAD

**Issue by mcse3010** [NimbusAPI/Nimbus#228]
When logging using the Nimbus.Logger.Log4net.Log4netlogger, the log meesages submitted for formatting to the logger are in an incorrect (perhaps Serilog?) format.

When log messages are submitted to DebugFormat with arguments like this call:
_log.DebugFormat(format, args)

The format should be in standard String.Format form:  {0}, {1}, ...

Instead the incoming format looks like this (this is just one of the many):
{DispatchAction} {ShortMessageTypeName} ({MessageId}) to {QueueOrTopicPath} ({@MessageMetadata})

Clearly these are not the standard indexed String.Format formats but appear to be some sort of other log format.

**Comment by uglybugger** [comment]
Oops. That's not supposed to happen.

We generally use the Serilog format internally and then map the tokens back
to a string.Format-friendly template. It looks like that's missing for the
log4net logger.

I'll take a look in the next day or so.




On Monday, 11 January 2016, Chadwick Posey <notifications@github.com> wrote:

> When logging using the NimbusLoggerLog4netLog4netlogger, the log meesages
> submitted for formatting to the logger are in an incorrect (perhaps
> Serilog?) format
>
> When log messages are submitted to DebugFormat with arguments like this
> call:
> _logDebugFormat(format, args)
>
> The format should be in standard StringFormat form: {0}, {1},
>
> Instead the incoming format looks like this (this is just one of the many):
> {DispatchAction} {ShortMessageTypeName} ({MessageId}) to
> {QueueOrTopicPath} ({@MessageMetadata})
>
> Clearly these are not the standard indexed StringFormat formats but appear
> to be some sort of other log format
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NimbusAPI/Nimbus/issues/228>.
>


-- 
<http://www.customsig.com/Signature/Link/andrewh%40uglybugger.org>

**Comment by ma499** [comment]
I created a [pull request](https://github.com/NimbusAPI/Nimbus/pull/200) months ago to fix this. Currently no conflicts with master.

**Comment by uglybugger** [comment]
Oops - I completely missed that one. Thanks, @ma499 :)  I'll merge it shortly.

**Comment by uglybugger** [comment]
Fixed by #200. Thanks, @ma499 :)
