### ISSUE TITLE
Anubus: Thoughts?

### ISSUE THREAD

**Issue by markalanevans** [NimbusAPI/Nimbus#229]
Hey guys, we are evaluating our options and we see Nimbus & Anubus. https://github.com/rebase42/Anubus

What are your thoughts?

**Comment by DamianMac** [comment]
I hadn't seen that yet.

So we've done some work over december to split out the Windows Service Bus libraries and make pluggable transports. That would let us do a newer Azure SDK transport to take advantage of those features. Have a read of this #221 

More exciting though is the work we've started with redis, it's proving to be orders of magnitude faster than ASB or WSB. 

We're hoping to be able to release this as 3.0 by the end of the month (ish). We're having a chat today about a few decisions that we need to make.

**Comment by markalanevans** [comment]
Sweet. Would love to hear about it. The Service bus concept is something we are educating our selves on right now. So keeping things simple (Redis) would be great.   Where will you be posting your "updates", so i can follow your progress?
