### ISSUE TITLE
Nimbus.Transports.WindowsServiceBus not available on NuGet

### ISSUE THREAD

**Issue by markalanevans** [NimbusAPI/Nimbus#231]
While trying to setup the Transport i needed to add Nimbus.Transports.WindowsServiceBus to my project.

But this Nimbus.Transports.WindowsServiceBus is not available via NuGet.

**Comment by markalanevans** [comment]
I found it here: [https://www.myget.org/gallery/nimbusapi](https://www.myget.org/gallery/nimbusapi)

**Comment by DamianMac** [comment]
Are you working from source ? We've not published the new changes to nuget.org yet.

**Comment by markalanevans** [comment]
I was just trying to add your packages using the Nuget package manager in VS, All your other packages were available, but not this one "Nimbus.Transports.WindowsServiceBus".
