### ISSUE TITLE
Messages removed if no subscribers???

### ISSUE THREAD

**Issue by markalanevans** [NimbusAPI/Nimbus#232]
If a message is published, and there are no subscribers, is expected functionality such that the message is immediately removed?

**Comment by DamianMac** [comment]
On the Azure side ? Yeah it won't place the message anywhere if there are no subscriber queues.

**Comment by markalanevans** [comment]
Ok. Cool. 

So i'll have to read about configurations and suggestions for how long messages should be persisted if subscribers go down.

Any gotchas you have come across for this?  ex a Subscriber system goes down, we don't want to loose those messages.  Perhaps there is some strategy here.
