### ISSUE TITLE
Topic & Subscribers Created, but Not processed by subscriber. No Messages on Topic

### ISSUE THREAD

**Issue by markalanevans** [NimbusAPI/Nimbus#234]
Hey Gents,

So i have my webjob & webapp running. Looking at the portal or in VS i can see that the topic was created by Nimbus & that my web job is running and a a subscription is attached to the OrderPlacedEvent.

![ScreenShot of ServiceBus](https://www.evernote.com/l/AJFjEht7Km1PjpxVzCwus1-rc-XdQubJrOMB/image.png)

I can login to the Azure portal and see that requests are made, but i'm not seeing the messages get "stuck" in the queue or being processed by the subscriber.

Here are the settings that Nimbus has setup for this Topic/Subscription

![Screenshot of Topic Configs](https://www.evernote.com/l/AJFAlNTVUmBGdJWmpqi3onfSm_XC--pi0QkB/image.png)

**How can i find out what i might have configured incorrectly?**

By the way, i'm testing the worker and app locally, but connecting to the Azure Service bus, is there some sort of setting or authentication I  need to configure for the ServiceBus?

**Comment by markalanevans** [comment]
I'm wondering if perhaps the Bus is not Starting. I'm not seeing any of the logging that it looks like I should be seeing when this [code](https://github.com/NimbusAPI/Nimbus/blob/master/src/Nimbus/Bus.cs#L96-L126) gets triggered 

```c#
using System;
using System.Configuration;
using System.Reflection;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Autofac;
using CoffeeTalk.Cashier.Handlers;
using Microsoft.Azure.WebJobs;
using Nimbus;
using Nimbus.Configuration;
using Nimbus.Infrastructure;
using Nimbus.Infrastructure.Events;
using Nimbus.Infrastructure.Logging;
using Nimbus.Transports.WindowsServiceBus;
using CoffeeTalk.Customer.Messages;
using CoffeeTalk.Cashier.Messages;
using Serilog;
using Nimbus.Logger.Serilog;


namespace CoffeeTalk.Cashier
{
    // To learn more about Microsoft Azure WebJobs SDK, please see http://go.microsoft.com/fwlink/?LinkID=320976
    class Program
    {

        // Please set the following connection strings in app.config for this WebJob to run:
        // AzureWebJobsDashboard and AzureWebJobsStorage
        static void Main()
        {
            Log.Logger = new LoggerConfiguration()
                .WriteTo.ColoredConsole()
                .MinimumLevel.Verbose()
                .CreateLogger();

            Log.Information("No one listens to me!");

            var builder = new ContainerBuilder();
            builder.RegisterType<Modules.Cashier>().AsImplementedInterfaces().SingleInstance();
            SetUpBus(builder);
            
            Log.Information("Cashier is waiting...");
            var container = builder.Build();

            // The following code ensures that the WebJob will be running continuously
            var host = new JobHost();
            host.RunAndBlock();
        }

        public static void startingUp()
        {
            Log.Information("Activating...");
        }
        private static void SetUpBus(ContainerBuilder builder)
        {
            Log.Information("SetUpBus...");
            var connectionString = ConfigurationManager.AppSettings["AzureConnectionString"];

            // Register you logger
                        builder.RegisterType<SerilogStaticLogger>()
                            .AsImplementedInterfaces()
                            .SingleInstance();
            
            // This is how you tell Nimbus where to find all your message types and handlers.
            var typeProvider = new AssemblyScanningTypeProvider(Assembly.GetExecutingAssembly(),
                typeof (CashierChargeCustomerHandler).Assembly,
                typeof (OrderPlacedEvent).Assembly);


            builder.RegisterNimbus(typeProvider);
            builder.Register(componentContext => new BusBuilder().Configure()
                    .WithTransport(new WindowsServiceBusTransportConfiguration()
                        .WithConnectionString(connectionString)
                    )
                    .WithNames("Cashier", Environment.MachineName)
                    .WithTypesFrom(typeProvider)
                    .WithAutofacDefaults(componentContext)
                    .Build()
                 )
                .As<IBus>()
                .AutoActivate()
                .OnActivated(c => c.Instance.Start())
                .SingleInstance();
            Log.Information("Done setting up bus.");
        }
        
    }
}
```

**Comment by KodrAus** [comment]
I'm not really familiar with webjobs, but any issues I've had in the past with messages _just not getting processed_ have been because of dependency injection issues. Can you be sure that the assemblies you're passing to the `AssemblyScanningTypeProvider` are available to the webjob? And that any dependencies in your handler's constructor are in the DI container?

**Comment by gertjvr** [comment]
Curious have you read this post? http://bendetat.com/bundling-and-deploying-azure-webjobs-in-a-web-app.html

**Comment by gertjvr** [comment]
Here is an example of nimbus and webjob https://github.com/michael-wolfenden/NimbusWebJob

**Comment by markalanevans** [comment]
@KodrAus Everything seems right, but it could very likely be a DI issue. I'm struggling, how can I identify it? I don't see any logging from Nimbus's internals.

**Comment by markalanevans** [comment]
@KodrAus I did a little debugging and inside the inspector for the AutoFac registrations, i notice i see a few of my classes there, but I didn't see the IBusEvent object.

![https://www.evernote.com/l/AJHALiQXOqlJR6tbFLQV9Gn-qd4falA83pcB/image.png](https://www.evernote.com/l/AJHALiQXOqlJR6tbFLQV9Gn-qd4falA83pcB/image.png)

In my program.cs

I use the CoffeeTalk.Customer.Messages project.

Which has this:

```
using Nimbus.MessageContracts;

namespace CoffeeTalk.Customer.Messages
{
    public class OrderPlacedEvent : IBusEvent
    {
        public int OrderId { get; set; }
        public string Type { get; set; }
        public string Size { get; set; }

    }
}
```

And as you in my earlier post, I registered "OrderPlacedEvent" with the container.

Should I see the "OrderPlacedEvent" event in the Registrations?

**Comment by markalanevans** [comment]
@gertjvr Thank you for that, once i get the basics working, it looks like you have some great work there for making deploying Nimbus WebJobs play well together.

@gertjvr Do you always use a Windows Service bus for local dev, rather than just connecting to an Azure Service bus remotely ?  

From what i'm reading, NimbusAPI might be pulling out Transports or at least separating them(https://github.com/NimbusAPI/Nimbus/issues/221 talk of it near bottom).

**Comment by KodrAus** [comment]
@markalanevans `IBusEvent` isn't something that'll be registered with the container, because you could have lots of different events flying around the one application.

You could also try removing the `.AutoActivate().OnActivated(c => c.Instance.Start());` part in your BusBuilder, and call `var bus = container.Resolve<IBus>()` in your Main method. Then you could inspect what the bus thinks it's doing.

**Comment by gertjvr** [comment]
@markalanevans have always used windows service bus for local development, we had a large team working on the same solution and have a common azure service bus would have been a disaster. 

And creating a azure service bus per developer would have been to costly.

Think that was the main reason why nimbus started out targeting wsb with the hope that wsb would keep up with azure servicebus.

**Comment by gertjvr** [comment]
I used nimbus to create a simple chat app to learn, I always learn better seeing examples of how other have written things. https://github.com/gertjvr/chatterbox

**Comment by markalanevans** [comment]
@KodrAus , @gertjvr pointed me a bit deeper into getting the logging working and it looks like that was the problem, I just wasn't seeing my messages because Logging was not working.
I have updated the Wiki on logging with an example.

Thank you both so much.
