### ISSUE TITLE
Nimbus LifeCycle from Dispatch to Handling Message.

### ISSUE THREAD

**Issue by markalanevans** [NimbusAPI/Nimbus#236]
I just got a message on the queue.

![https://www.evernote.com/l/AJGtt0RzVp5LYJrBG8ilojd8eoh0vuSuQyUB/image.png](https://www.evernote.com/l/AJGtt0RzVp5LYJrBG8ilojd8eoh0vuSuQyUB/image.png)

What are the phases from start to finish from Polling a topic, to dispatching to handling?

ex:

1. Poll Topic "OrderPlaced"
2. Dispatch Message
3. Lock Message
4. Wait.
5. Handle Message
etc.

**Comment by markalanevans** [comment]
It would also be interesting to understand the Push / Pull nature of Nimbus & Azure Service Bus.
Do subscriptions  long poll topics?

**Comment by uglybugger** [comment]
This is a good question. The answer changes (slightly) between v2 and v3. We should add it as a documentation task.

In answer to your specific questions: the sequence looks pretty much like:
- Long-poll on the queue or subscription
- Deserialize message
- Dispatch to pre-handler interceptor(s)
- Dispatch to handler
- Dispatch to post-handler or error interceptor(s)

If the message requires a reply then it will go through the same process as sending a message and the original requestor will apply the same long-poll + intercept + handle approach when it receives a reply.

One change between v2 and v3 is the removal of message locking. Message locking caused us no end of pain and for only a tiny amount of gain. In v3 it's been removed in favour of having nodes themselves resubmit messages for redelivery if handling fails. There's a minor chance here that if a node fails permanently while it's handling a message then it might not redeliver but there are other ways to compensate for that.
