### ISSUE TITLE
BatchingMessageSender stops performing lazy flushes

### ISSUE THREAD

**Issue by AmosC** [NimbusAPI/Nimbus#249]
We've encountered an issue in Nimbus version 2.0.0.98 where messages are no longer being lazily flushed, but still continue to be flushed when the _maximumBatchSize of 100 is reached.

Restarting the application resolves the issue until it happens again, any messages batched in memory at the time is lost.

We believe the issue stems from FlushMessagesLazily()'s premature assignment of _lazyFlushTask to null due to the behaviour of awaiting a task which potentially exhibits synchronous behaviour[1].  

When the Send() method assigns _lazyFlushTask it immediately begins execution of FlushMessageLazily().  If the await on the delay happens to be synchronous, then FlushMessageLazily()'s assignment of _lazyFlushTask's to null happens *prior* to Send()'s assignment of _lazyFlushTask.  

This leads to a situation where _lazyFlushTask is never set to null again, consequently no further lazy flushes are performed.

[1] - "In some cases, the amount of work required to complete the operation is less than the amount of work it would take to launch the operation asynchronously (e.g. reading from a stream where the read can be satisfied by data already buffered in memory). In such cases, the operation may complete synchronously, returning a Task that has already been completed."
http://stackoverflow.com/questions/17507374/why-does-my-asynchronous-code-run-synchronously-when-debugging

**Comment by DamianMac** [comment]
Have pulled in your PR to the v2maint branch
