### ISSUE TITLE
Is it possible to only subscribe to events with certain property value?

### ISSUE THREAD

**Issue by fenix2222** [NimbusAPI/Nimbus#252]
Lets say I have an app at every client site that runs on premise. All those apps publish some type of event to Service Bus, each event with have SiteId. Now, there will be another app running elsewhere, that needs to subscribe to specific events from only selected list of sites. I cannot find a way to subscribed to events filtered by property (i.e. filtered by SiteId in this case). Is it possible? I don't want to create event types per site and I don't want to get all events and then filter it later somewhere else...

**Comment by drewfreyling** [comment]
Service bus allows you to create rules that you can filter on. Have a look at the `Microsoft.ServiceBus.Messaging.Rule` class.

**Comment by fenix2222** [comment]
@drewfreyling  How do you use these rules in Nimbus?

**Comment by DamianMac** [comment]
You can't at the moment. We started looking at an API for defining them but didn't finish it.

**Comment by fenix2222** [comment]
Ok. Are there any plans to introduce those?

**Comment by lukeschafer** [comment]
It's not hard to do yourself by using the pathfactory to identify the
subscription. Drew might be willing to dump some code... I've done it, but
don't work at that place any more, so don't have the code on hand

**Comment by fenix2222** [comment]
@lukeschafer Sample code would be appreciated. If it is too hard to do with Nimbus, then we will just use barebone Azure Service Bus API. I noticed Nimbus has custom IRouter interface, so I thought taht would be the one to try to customize

**Comment by drewfreyling** [comment]
@fenix2222 I'll see if I can get approval to put the code out in the open.

**Comment by fenix2222** [comment]
@drewfreyling thanks. Is Nimbus dead? Haven't heard any updates and it doesn't support v3 of azure service bus. Nimbus 3 was supposed to be out but last blog about it is from April 2016
