### ISSUE TITLE
When does it really make sense to use a project like Nimbus vs Hangfire?

### ISSUE THREAD

**Issue by markalanevans** [NimbusAPI/Nimbus#257]
Our immediate need is background processing.
Both provide this, however management is full featured(built in UI) and deployment is simpler with Hangfire, but a service bus does seem like it could be more robust.

Aside from sending emails and post processing data. What are some pretty common examples that make using a Service Bus the right choice over http://hangfire.io/ when dealing with large web application?

**Comment by DamianMac** [comment]
Maybe the gitter channel is a better spot for this
