### ISSUE TITLE
Question: Are there any plans on supporting creating partitioned azure queues?

### ISSUE THREAD

**Issue by darrencamp** [NimbusAPI/Nimbus#262]
I may have a need to create partitioned Azure Queues. I can create them manually but I was wondering if there was any work in the pipeline for supporting their creation in Nimbus?

If not I'll give it a go and submit a PR for it.

**Comment by DamianMac** [comment]
Hi @darrencamp did you ever do need this? 
We have no plans for it, but if you'd like to have a crack at it I'll happy accept :)
