### ISSUE TITLE
Memory leak in Nimbus.Infrastructure.Dispatching.SubsequentDispatchContext

### ISSUE THREAD

**Issue by HEskandari** [NimbusAPI/Nimbus#267]
I have an app with creeping memory usage over time, and by that I mean with the rate of 200/300 message per second you can visibility see the memory usage grow in task manager. It gets to a point that the message processing rate drops and eventually the process comes to a halt.

Upon getting some dumps and comparing them, I can see the number of Nimbus.Infrastructure.Dispatching.SubsequentDispatchContext grow substantially over time.

This is from a memory dump:

Count    TotalSize    Class Name
162281    6491240    Nimbus.Infrastructure.Dispatching.SubsequentDispatchContext

Any ideas what might be causing this? I'm using Nimbus 2.0.0.98.

**Comment by teyc** [comment]
I've been chasing this too. This line looks suspicious? 

https://github.com/NimbusAPI/Nimbus/blob/master/src/Nimbus/ConcurrentCollections/ThreadSafeDictionary.cs#L55
