### ISSUE TITLE
NuGet packages from myget.org only shows 50 latest versions

### ISSUE THREAD

**Issue by bjoka042** [NimbusAPI/Nimbus#269]
We are currently using Nimbus v3.0.0.816. 
When the solution tries to resolve/download missing packages the package cannot be found.

I looked at some api endpoint for myget.org and it looks like it only displays the 50 latest packages.
https://www.myget.org/F/nimbusapi/api/v3/query

Should we be forced to upgrade?

To replicate: Remove package from current user account .nuget store aswell.

**Comment by DamianMac** [comment]
Have finally pushed it to Nuget
