### ISSUE TITLE
Event subscription naming does not use fully-qualified handler type name

### ISSUE THREAD

**Issue by flakey-bit** [NimbusAPI/Nimbus#274]
The implementation of `PathFactory::SubscriptionNameFor()` currently uses `handlerType.Name`. It should use `.FullName` because otherwise an event subscription will get lost if there are two handlers for the same event type which happen to be named the same (but under different namespaces).

**Comment by drewfreyling** [comment]
@flakey-bit is this a problem for both v2 and v3?

**Comment by flakey-bit** [comment]
Yes it affects both versions.

**Comment by drewfreyling** [comment]
Can you add this to the V2 repo as well?

**Comment by DamianMac** [comment]
From memory this is because of queue name length restrictions in ASB. I'd have to go double check that though. 
We could throw on registration if you had two handlers with the same name for the same message though?

**Comment by flakey-bit** [comment]
The code already (currently) handles names being too long by hashing the name and adding the hash as a suffix. So it should be a simple fix.

**Comment by DamianMac** [comment]
Cool, want to have a crack at it?

**Comment by flakey-bit** [comment]
I'll take a look if I get a spare moment :)

**Comment by drewfreyling** [comment]
@flakey-bit any progress?

**Comment by flakey-bit** [comment]
Apologies for leading you on - I don't think I'll realistically ever have time to look at this.
