### ISSUE TITLE
Release dotnet core

### ISSUE THREAD

**Issue by DamianMac** [NimbusAPI/Nimbus#283]
This will be a bit brief.

There's a `netcore-take2` branch which is a working, Dotnet Core port which will be 4.0.

A few things left to do on it.

- [ ] Clean up documentation
- [ ] AMQP Transport (Azure and Windows SB libraries will be deprecated) #284 
- [ ] Kafka Transport

**Comment by dicko2** [comment]
Still planning on kafka support?

**Comment by DamianMac** [comment]
This has changed a bit.
I've been using Azure again a lot, so the `develop` branch which is 4.* on Myget is a .net core port with a big focus on Azure. I just rolled back in large message support.
We've got a partly working amqp transport too.

Kafka hasn't happened, I know @uglybugger wanted to do one but he's not working with it at the moment. I have no need for it. If you wanted to have a crack through @dicko2 that could be fun :)
