### ISSUE TITLE
Required permissions

### ISSUE THREAD

**Issue by RTTrickster** [NimbusAPI/Nimbus#288]
Hi team, not an issue, more a request for clarification please. 

If running Nimbus service bus as Windows Services, what permissions are required for the services to run as? Is Local System sufficient? Does it need local Administrator? Something else? 

Thank you!

**Comment by DamianMac** [comment]
Hi @RTTrickster 
I think by default it logs on as Administrator (at least on my installs that is how it is).
However I wouldn't rely on it anymore, I don't think it's even available for download anymore unfortunately.
