### ISSUE TITLE
AzureQueueManager does not update descriptions if they have changed

### ISSUE THREAD

**Issue by bradleyboveinis** [NimbusAPI/Nimbus#74]
The EnsureXXXExists() commands on AzureQueueManager only checks if the queue/topic/subscription exists, however if the description changes after creation of the queue/topic/subscription, nimbus will not update the descriptions.

An appropriate place to check for correctness and update if required may be in the WarmUp method, after task0 and task1 have completed.

**Comment by uglybugger** [comment]
This is now done in the AzureQueueManager. When a queue/topic creation fails because one already exists, Nimbus immediately attempts to update its description instead.
